name: "DEV DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "wbl-terraform-statefile"
      aws-lock-dynamodb-table: "wbl-terraform-lock"
