name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::196157324271:role/github-actions-wilsonleandro-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "wilsonleandro-us-east-1-terraform-infra"
      aws-lock-dynamodb-table: "wilsonleandro-us-east-1-terraform-infra-lock"
